# Generated by Django 5.1.1 on 2024-10-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_teamstanding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_date']},
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('home_team', 'away_team', 'match_date')},
        ),
    ]
