# Generated by Django 5.1.1 on 2024-11-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscategory',
            name='description',
        ),
    ]
