# Generated by Django 5.1.1 on 2024-10-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(default='Kenyan', max_length=50),
        ),
    ]
