# Generated by Django 5.1.1 on 2024-11-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_player_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('stars', 'Ulinzi Stars'), ('starlets', 'Ulinzi Starlets'), ('youths', 'Ulinzi Youths')], max_length=100),
        ),
    ]
