# Generated by Django 5.1.1 on 2024-11-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('stars', 'Ulinzi Stars'), ('starlets', 'Ulinzi Starlets'), ('youths', 'Ulinzi Youths')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
