# Generated by Django 5.1.1 on 2024-11-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_player_team_delete_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='nationality',
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='player-images/'),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('military', 'Military'), ('civilian', 'Civilian')], default='military', max_length=50),
        ),
    ]
