# Generated by Django 5.1.1 on 2024-11-01 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=30)),
                ('member_number', models.CharField(default=None, max_length=10, unique=True)),
                ('membership', models.CharField(choices=[('regular', 'Regular'), ('associate', 'Associate'), ('guest', 'Guest')], default='regular', max_length=20)),
                ('baptism_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('baptism_date', models.DateField(blank=True, default=None, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=25)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('mobile', models.CharField(max_length=40, null=True)),
                ('residence', models.CharField(default='Nakuru', max_length=40)),
                ('postal_address', models.CharField(default='20100', max_length=40)),
                ('date_joined', models.DateField(blank=True, default=None, null=True)),
                ('date_left', models.DateField(blank=True, default=None, null=True)),
                ('status', models.BooleanField(default=False)),
                ('role', models.CharField(default='Member', max_length=50)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
