# Generated by Django 5.1.1 on 2024-11-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fan',
            name='baptism_date',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='baptism_status',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='date_left',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='member_number',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='postal_address',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='residence',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='role',
        ),
        migrations.AlterField(
            model_name='fan',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
