# Generated by Django 5.1.1 on 2024-11-04 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='away_team',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_purchased',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_number',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_code_data',
            field=models.CharField(default='nsnsn', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved')], default='available', max_length=10),
        ),
    ]
