# Generated by Django 5.1.1 on 2024-11-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_away_team_match_name_remove_match_home_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code_data',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
