# Generated by Django 5.1.1 on 2024-11-05 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_lineup_matchhighlight'),
        ('tickets', '0003_ticket_qr_code_image_alter_ticket_qr_code_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
